# dev enviroment setup

version: '2'
services:

  web:
    ports:
      # Expose Emoncms on localhost port 8080
      - 8080:80
    volumes:
      # Mount emoncms files from local FS for dev
      - ../../energylocal/emoncms:/var/www/emoncms
      - ../../energylocal/cydynni/www/club:/var/www/emoncms/Modules/club
      - ../../energylocal/cydynni/www/account:/var/www/emoncms/Modules/account
      - ../../energylocal/cydynni/www/data:/var/www/emoncms/Modules/data
      - ../../energylocal/cydynni/www/tariff:/var/www/emoncms/Modules/tariff
      - ../app:/var/www/emoncms/Modules/app
      - ../club2:/var/www/emoncms/Modules/club2
      - ../demandshaper/demandshaper-module:/var/www/emoncms/Modules/demandshaper
      - ../device:/var/www/emoncms/Modules/device
      - ../find:/var/www/emoncms/Modules/find
      - ../graph:/var/www/emoncms/Modules/graph
      # - ../input:/var/www/emoncms/Modules/input
      - ../postprocess/postprocess-module:/var/www/emoncms/Modules/postprocess
      # - ../process:/var/www/emoncms/Modules/process
      - ../provision:/var/www/emoncms/Modules/provision
      - ../remoteaccess-server/remoteaccess-module:/var/www/emoncms/Modules/remoteaccess
      # - ../schedule:/var/www/emoncms/Modules/schedule
      - ../sync/sync-module:/var/www/emoncms/Modules/sync
      # - ../time:/var/www/emoncms/Modules/time
      # - ../user:/var/www/emoncms/Modules/user
      # - ../vis:/var/www/emoncms/Modules/vis
      - ../:/opt/emoncms/modules
      - ../../energylocal/cydynni:/opt/emoncms/modules/cydynni
      - ./phpfina:/var/lib/phpfina
      - ./log:/var/log/emoncms
    env_file:
      # Use default enviroment variables file for dev
      - 'default.docker-env'

  db:
    ports:
      - 3306:3306
    env_file:
      - 'default.docker-env'

  redis:
    ports:
      - 6379:6379
    env_file:
      - 'default.docker-env'

  # Consider adding mosquitto broker
  mqtt:
    ports:
      - 1883:1883
    env_file:
      - 'default.docker-env'
